export const rolePermissions: Record<string, string[]> = {
  superadmin: ['auth:read', 'users:read', 'users:write', 'companies:read', 'companies:write', 'customers:read', 'customers:write', 'products:read', 'products:write', 'categories:read', 'categories:write', 'warehouses:read', 'warehouses:write', 'inventory:read', 'inventory:write', 'quotes:read', 'quotes:write', 'purchases:read', 'purchases:request', 'purchases:approve', 'purchases:write', 'finance:read', 'finance:write', 'employees:read', 'employees:write', 'departments:read', 'departments:write', 'attendance:read', 'attendance:write', 'projects:read', 'projects:write', 'audit:read', 'suppliers:read', 'suppliers:write', 'sales:read', 'sales:write', 'invoices:read', 'invoices:write', 'reports:read'],
  company_admin: ['auth:read', 'users:read', 'users:write', 'companies:read', 'companies:write', 'customers:read', 'customers:write', 'products:read', 'products:write', 'categories:read', 'categories:write', 'warehouses:read', 'warehouses:write', 'inventory:read', 'inventory:write', 'quotes:read', 'quotes:write', 'purchases:read', 'purchases:request', 'purchases:approve', 'purchases:write', 'finance:read', 'finance:write', 'employees:read', 'employees:write', 'departments:read', 'departments:write', 'attendance:read', 'attendance:write', 'projects:read', 'projects:write', 'audit:read', 'suppliers:read', 'suppliers:write', 'sales:read', 'sales:write', 'invoices:read', 'invoices:write', 'reports:read'],
  manager: ['auth:read', 'users:read', 'companies:read', 'customers:read', 'customers:write', 'products:read', 'products:write', 'categories:read', 'categories:write', 'warehouses:read', 'warehouses:write', 'inventory:read', 'inventory:write', 'quotes:read', 'quotes:write', 'purchases:read', 'purchases:request', 'purchases:approve', 'purchases:write', 'finance:read', 'finance:write', 'employees:read', 'employees:write', 'departments:read', 'departments:write', 'attendance:read', 'attendance:write', 'projects:read', 'projects:write', 'audit:read', 'suppliers:read', 'suppliers:write', 'sales:read', 'sales:write', 'invoices:read', 'invoices:write', 'reports:read'],
  employee: ['auth:read', 'customers:read', 'customers:write', 'products:read', 'products:write', 'categories:read', 'warehouses:read', 'inventory:read', 'quotes:read', 'quotes:write', 'purchases:read', 'purchases:request', 'finance:read', 'employees:read', 'departments:read', 'attendance:read', 'attendance:write', 'projects:read', 'projects:write', 'suppliers:read', 'suppliers:write', 'sales:read', 'sales:write', 'invoices:read', 'reports:read'],
  viewer: ['auth:read', 'customers:read', 'products:read', 'categories:read', 'warehouses:read', 'inventory:read', 'quotes:read', 'purchases:read', 'finance:read', 'employees:read', 'departments:read', 'attendance:read', 'projects:read', 'audit:read', 'suppliers:read', 'sales:read', 'invoices:read', 'reports:read']
};

export function permissionsForRole(role: string) {
  return rolePermissions[role] ?? [];
}